# 2.3 업무시간/비 업무시간 변수 생성
- 휴일이 아닌날의 오전8시~ 오후 7시 사이는 일하는 시간으로 지정
- work_time변수에 기록

In [2]:
import pandas as pd

In [5]:
# data = pd.read_csv('data/train_set/2.2data_weather_watching.csv')
data = pd.read_csv('data/test_set/2.data_add_feature1.csv')
data.head()

,broadcast_date,broadcast_time,broadcast_code,product_code,product_name,product_category,unit_price,handling_amount,off_day,date,...,rain_seoul,humid_seoul,snow_seoul,temperature_busan,rain_busan,humid_busan,snow_busan,season,day_dup,week_dup
0,2020-06-01 06:20:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN,False,2020-06-01,...,0.1,90,0.0,18.6,0.0,91,0.0,3,1.0,1.0
1,2020-06-01 06:40:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN,False,2020-06-01,...,0.1,90,0.0,18.6,0.0,91,0.0,3,2.0,2.0
2,2020-06-01 07:00:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN,False,2020-06-01,...,0.0,86,0.0,19.2,0.0,87,0.0,3,3.0,3.0
3,2020-06-01 07:20:00,20.000000,100445,202278,쿠미투니카 쿨 레이시 란쥬쉐이퍼&팬티,속옷,69900,NaN,False,2020-06-01,...,0.0,86,0.0,19.2,0.0,87,0.0,3,1.0,1.0
4,2020-06-01 07:40:00,20.000000,100445,202278,쿠미투니카 쿨 레이시 란쥬쉐이퍼&팬티,속옷,69900,NaN,False,2020-06-01,...,0.0,86,0.0,19.2,0.0,87,0.0,3,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2886,2020-07-01 00:20:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN,False,2020-07-01,...,0.0,85,0.0,21.0,0.0,74,0.0,3,1.0,1.0
2887,2020-07-01 00:40:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN,False,2020-07-01,...,0.0,85,0.0,21.0,0.0,74,0.0,3,2.0,2.0
2888,2020-07-01 01:00:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN,False,2020-07-01,...,0.0,87,0.0,20.8,0.0,77,0.0,3,3.0,3.0
2889,2020-07-01 01:20:00,20.000000,100261,200875,아놀드파마 티셔츠레깅스세트,의류,69900,NaN,False,2020-07-01,...,0.0,87,0.0,20.8,0.0,77,0.0,3,1.0,1.0
2890,2020-07-01 01:40:00,15.933333,100261,200875,아놀드파마 티셔츠레깅스세트,의류,69900,NaN,False,2020-07-01,...,0.0,87,0.0,20.8,0.0,77,0.0,3,2.0,2.0

In [7]:
# 전부 일하는 시간으로 초기화
data['working_time'] = True

In [8]:
# 휴일은 전부 일하지 않는 시간으로 지정
data.loc[data['off_day'] == True,'working_time'] = False

In [9]:
# 9시-6시를 회사에 있는 시간으로 할 때, 8시 - 7시를 working time, 나머지 시간을 집에있는 시간으로
data.loc[data['hour'].isin([6,7,20,21,22,23,0,1,2]),'working_time'] = False

In [10]:
data

,broadcast_date,broadcast_time,broadcast_code,product_code,product_name,product_category,unit_price,handling_amount,off_day,date,...,humid_seoul,snow_seoul,temperature_busan,rain_busan,humid_busan,snow_busan,season,day_dup,week_dup,working_time
0,2020-06-01 06:20:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN,False,2020-06-01,...,90,0.0,18.6,0.0,91,0.0,3,1.0,1.0,False
1,2020-06-01 06:40:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN,False,2020-06-01,...,90,0.0,18.6,0.0,91,0.0,3,2.0,2.0,False
2,2020-06-01 07:00:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN,False,2020-06-01,...,86,0.0,19.2,0.0,87,0.0,3,3.0,3.0,False
3,2020-06-01 07:20:00,20.000000,100445,202278,쿠미투니카 쿨 레이시 란쥬쉐이퍼&팬티,속옷,69900,NaN,False,2020-06-01,...,86,0.0,19.2,0.0,87,0.0,3,1.0,1.0,False
4,2020-06-01 07:40:00,20.000000,100445,202278,쿠미투니카 쿨 레이시 란쥬쉐이퍼&팬티,속옷,69900,NaN,False,2020-06-01,...,86,0.0,19.2,0.0,87,0.0,3,2.0,2.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2886,2020-07-01 00:20:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN,False,2020-07-01,...,85,0.0,21.0,0.0,74,0.0,3,1.0,1.0,False
2887,2020-07-01 00:40:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN,False,2020-07-01,...,85,0.0,21.0,0.0,74,0.0,3,2.0,2.0,False
2888,2020-07-01 01:00:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN,False,2020-07-01,...,87,0.0,20.8,0.0,77,0.0,3,3.0,3.0,False
2889,2020-07-01 01:20:00,20.000000,100261,200875,아놀드파마 티셔츠레깅스세트,의류,69900,NaN,False,2020-07-01,...,87,0.0,20.8,0.0,77,0.0,3,1.0,1.0,False
2890,2020-07-01 01:40:00,15.933333,100261,200875,아놀드파마 티셔츠레깅스세트,의류,69900,NaN,False,2020-07-01,...,87,0.0,20.8,0.0,77,0.0,3,2.0,2.0,False

In [11]:
data.to_csv('data/test_set/2.3work_time.csv',index = False)