## 과거의 총 매출액 변수 생성

In [1]:
import pandas as pd
import numpy as np
import pdb

In [3]:
data=pd.read_csv('data/test_set/2.3work_time.csv')
data

,broadcast_date,broadcast_time,broadcast_code,product_code,product_name,product_category,unit_price,handling_amount,off_day,date,...,humid_seoul,snow_seoul,temperature_busan,rain_busan,humid_busan,snow_busan,season,day_dup,week_dup,working_time
0,2020-06-01 06:20:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN,False,2020-06-01,...,90,0.0,18.6,0.0,91,0.0,3,1.0,1.0,False
1,2020-06-01 06:40:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN,False,2020-06-01,...,90,0.0,18.6,0.0,91,0.0,3,2.0,2.0,False
2,2020-06-01 07:00:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN,False,2020-06-01,...,86,0.0,19.2,0.0,87,0.0,3,3.0,3.0,False
3,2020-06-01 07:20:00,20.000000,100445,202278,쿠미투니카 쿨 레이시 란쥬쉐이퍼&팬티,속옷,69900,NaN,False,2020-06-01,...,86,0.0,19.2,0.0,87,0.0,3,1.0,1.0,False
4,2020-06-01 07:40:00,20.000000,100445,202278,쿠미투니카 쿨 레이시 란쥬쉐이퍼&팬티,속옷,69900,NaN,False,2020-06-01,...,86,0.0,19.2,0.0,87,0.0,3,2.0,2.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2886,2020-07-01 00:20:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN,False,2020-07-01,...,85,0.0,21.0,0.0,74,0.0,3,1.0,1.0,False
2887,2020-07-01 00:40:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN,False,2020-07-01,...,85,0.0,21.0,0.0,74,0.0,3,2.0,2.0,False
2888,2020-07-01 01:00:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN,False,2020-07-01,...,87,0.0,20.8,0.0,77,0.0,3,3.0,3.0,False
2889,2020-07-01 01:20:00,20.000000,100261,200875,아놀드파마 티셔츠레깅스세트,의류,69900,NaN,False,2020-07-01,...,87,0.0,20.8,0.0,77,0.0,3,1.0,1.0,False
2890,2020-07-01 01:40:00,15.933333,100261,200875,아놀드파마 티셔츠레깅스세트,의류,69900,NaN,False,2020-07-01,...,87,0.0,20.8,0.0,77,0.0,3,2.0,2.0,False

In [18]:
data['pastAvg_diff']=np.nan
data

,broadcast_date,broadcast_time,broadcast_code,product_code,product_name,product_category,unit_price,handling_amount,off_day,date,...,snow_busan,pmWarning_seoul,pmWarning_busan,season,day_dup,week_dup,max_watching,avg_watching,working_time,pastAvg_diff
0,2019-01-01 06:00:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000.0,True,2019-01-01,...,0.0,False,False,1,1.0,1.0,0.000,0.0000,False,NaN
1,2019-01-01 06:00:00,20.0,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000.0,True,2019-01-01,...,0.0,False,False,1,1.0,1.0,0.000,0.0000,False,NaN
2,2019-01-01 06:20:00,20.0,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000.0,True,2019-01-01,...,0.0,False,False,1,2.0,2.0,0.000,0.0000,False,NaN
3,2019-01-01 06:20:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000.0,True,2019-01-01,...,0.0,False,False,1,2.0,2.0,0.000,0.0000,False,NaN
4,2019-01-01 06:40:00,20.0,100346,201079,테이트 여성 셀린니트3종,의류,39900,9337000.0,True,2019-01-01,...,0.0,False,False,1,3.0,3.0,0.000,0.0000,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35370,2019-12-31 23:20:00,20.0,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000,620000.0,False,2019-12-31,...,0.0,False,False,1,1.0,4.0,0.000,0.0000,False,NaN
35371,2019-12-31 23:40:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000,9149000.0,False,2019-12-31,...,0.0,False,False,1,2.0,5.0,0.038,0.0206,False,NaN
35372,2019-12-31 23:40:00,20.0,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000,15282000.0,False,2019-12-31,...,0.0,False,False,1,2.0,5.0,0.038,0.0206,False,NaN
35373,2019-12-31 23:40:00,20.0,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000,2328000.0,False,2019-12-31,...,0.0,False,False,1,2.0,5.0,0.038,0.0206,False,NaN
35374,2019-12-31 23:40:00,20.0,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,10157000.0,False,2019-12-31,...,0.0,False,False,1,2.0,5.0,0.038,0.0206,False,NaN

In [19]:
data

,broadcast_date,broadcast_time,broadcast_code,product_code,product_name,product_category,unit_price,handling_amount,off_day,date,...,snow_busan,pmWarning_seoul,pmWarning_busan,season,day_dup,week_dup,max_watching,avg_watching,working_time,pastAvg_diff
0,2019-01-01 06:00:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000.0,True,2019-01-01,...,0.0,False,False,1,1.0,1.0,0.000,0.0000,False,NaN
1,2019-01-01 06:00:00,20.0,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000.0,True,2019-01-01,...,0.0,False,False,1,1.0,1.0,0.000,0.0000,False,NaN
2,2019-01-01 06:20:00,20.0,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000.0,True,2019-01-01,...,0.0,False,False,1,2.0,2.0,0.000,0.0000,False,NaN
3,2019-01-01 06:20:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000.0,True,2019-01-01,...,0.0,False,False,1,2.0,2.0,0.000,0.0000,False,NaN
4,2019-01-01 06:40:00,20.0,100346,201079,테이트 여성 셀린니트3종,의류,39900,9337000.0,True,2019-01-01,...,0.0,False,False,1,3.0,3.0,0.000,0.0000,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35370,2019-12-31 23:20:00,20.0,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000,620000.0,False,2019-12-31,...,0.0,False,False,1,1.0,4.0,0.000,0.0000,False,NaN
35371,2019-12-31 23:40:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000,9149000.0,False,2019-12-31,...,0.0,False,False,1,2.0,5.0,0.038,0.0206,False,NaN
35372,2019-12-31 23:40:00,20.0,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000,15282000.0,False,2019-12-31,...,0.0,False,False,1,2.0,5.0,0.038,0.0206,False,NaN
35373,2019-12-31 23:40:00,20.0,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000,2328000.0,False,2019-12-31,...,0.0,False,False,1,2.0,5.0,0.038,0.0206,False,NaN
35374,2019-12-31 23:40:00,20.0,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,10157000.0,False,2019-12-31,...,0.0,False,False,1,2.0,5.0,0.038,0.0206,False,NaN

In [20]:

for i in range(len(data)):
    past_data = data.iloc[0:i]
    past_same_data = past_data.loc[past_data.product_code == data.loc[i].product_code]
    if(len(past_same_data) ==0):
        data.loc[i,'pastAvg_diff'] = np.nan
    else:
        pastAvg = past_same_data.handling_amount.mean()
        pastAvg_diff_ = data.loc[i].handling_amount-pastAvg
        data.loc[i,'pastAvg_diff'] = pastAvg_diff_

In [21]:
data.loc[0:30,['product_name','handling_amount','pastAvg_diff']]

                     product_name  handling_amount  pastAvg_diff
0                   테이트 남성 셀린니트3종        2099000.0           NaN
1                   테이트 여성 셀린니트3종        4371000.0           NaN
2                   테이트 여성 셀린니트3종        6955000.0     2584000.0
3                   테이트 남성 셀린니트3종        3262000.0     1163000.0
4                   테이트 여성 셀린니트3종        9337000.0     3674000.0
5                   테이트 남성 셀린니트3종        6672000.0     3991500.0
6                오모떼 레이스 파운데이션 브라        6819000.0           NaN
7                오모떼 레이스 파운데이션 브라       15689000.0     8870000.0
8                오모떼 레이스 파운데이션 브라       25370000.0    14116000.0
9   CERINI by PAT 남성 소프트 기모 릴렉스팬츠       16133000.0           NaN
10  CERINI by PAT 남성 소프트 기모 릴렉스팬츠       30061000.0    13928000.0
11  CERINI by PAT 남성 소프트 기모 릴렉스팬츠       53542000.0    30445000.0
12                    보코 리버시블 무스탕       16075000.0           NaN
13                    보코 리버시블 무스탕       25628000.0     9553000.0
14                    보코 리버시블 무스탕       49270000.0    28418500.0
15  CERINI by PAT 남성 풀패키지 기모니트 3종       48799000.0           NaN
16  CERINI by PAT 남성 풀패키지 기모니트 3종       97907000.0    49108000.0
17  CERINI by PAT 남성 풀패키지 기모니트 3종      112972000.0    39619000.0
18      크로커다일 The 편안한 코튼 브라팬티 4세트       24531000.0           NaN
19      크로커다일 The 편안한 코튼 브라팬티 4세트       49829000.0    25298000.0
20               에코라믹 통주물 스톤 냄비세트       33823000.0           NaN
21               에코라믹 통주물 스톤 냄비세트       59083000.0    25260000.0
22               에코라믹 통주물 스톤 냄비세트       99235000.0    52782000.0
23       오모떼 360도 텐션업 레이스 패키지 시즌4       32273000.0           NaN
24       오모떼 360도 텐션업 레이스 패키지 시즌4       79273000.0    47000000.0
25            그렉노먼 남성 구스다운 롱 벤치코트       11269000.0           NaN
26            그렉노먼 여성 구스다운 롱 벤치코트       20841000.0           NaN
27            그렉노먼 여성 구스다운 롱 벤치코트       47294000.0    26453000.0
28            그렉노먼 남성 구스다운 롱 벤치코트       40526000.0    29257000.0
29               뽕셰프 이봉원 특갈비탕 12팩       14113000.0           NaN
30               뽕셰프 이봉원 특갈비탕 12팩       32395000.0    18282000.0

In [22]:
data.to_csv('data/train_set/2.4pastAvg_diff.csv', index = False)